#!/bin/sh
#
# Cycle the ethernet ports up and then back down
# This has been found to drastically reduce overall power consumption
#

umask 077

start() {
	printf "Cycling both ethernet interfaces: "
	ifconfig eth0 up
	ifconfig eth1 up
	ifconfig eth0 down
	ifconfig eth1 down
	echo "OK"
}
stop() {
	true
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
